# -*- coding: utf-8 -*-
"""Insertion_Sort

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tiCR1yG_k6ofJglWIoISJclkENh-xyPf
"""

class insertion_sort:
  def __init__(self,arr,n):
    self.arr = arr
    self.n = n

  def sort(self):
    for j in range(1,n):
      key = self.arr[j]
      i=j-1
      while i>=0 and arr[i]>key:
        arr[i+1] = arr[i]
        i=i-1
      arr[i+1] = key
      print(arr)
    # print(arr)
    return arr

arr = [9,8,7,6,5,4,3,2,1]
n=len(arr)

sort = insertion_sort(arr,n)

arr1 = sort.sort()

arr1[0]

